cinemaproject/cinemaapp/urls.py
from . import views
from django.urls import path
app_name='cinemaapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add',views.add_movie,name='add_movie')
]

cinemaproject/cinemaproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cinemaproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cinemaapp.urls')),
    path('credentials/',include('credentials.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cinemaproject/credentials/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout')
]

cinemaproject/cinemaapp/models.py
from django.db import models

# Create your models here.
class Cinema(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to="gallery")

    def __str__(self):
        return self.name

cinemaproject/credentials/models.py
from django.db import models

# Create your models here.

cinemaproject/cinemaapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

from cinemaapp.models import Cinema


# Create your views here.
def index(request):
    obj=Cinema.objects.all()
    return render(request,"index.html",{'result':obj})

def detail(request, movie_id):
    movie=Cinema.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Cinema(name=name,desc=desc,year=year,img=img)

    return render(request,"add.html")

# def addition(request):
#     x=int(request.GET['num1'])
#     y=int(request.GET['num2'])
#     add=x+y
#     sub=x-y
#     multi=x*y
#     div=x/y
#     return render(request,"result.html",{'subtraction':sub,'addition':add,'multiplication':multi,'division':div})

cinemaproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        firstname=request.POST['first_name']
        lastname=request.POST['last_name']
        email=request.POST['email']
        password=request.POST['password']
        cpassword=request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username):
                messages.info(request,"username is taken")
                return redirect('register')
            elif User.objects.filter(email=email):
                messages.info(request,"email is already taken")
                return redirect('register')
            else:
                user=User.objects.create_user(username=username,first_name=firstname,last_name=lastname,email=email,password=password)
                user.save()
                messages.info(request,"Registration completed succesfully")
                return redirect('login')

        else:
            messages.info(request,"Password not match")
            return redirect('register')
        return redirect('/')
    return render(request,"register.html")
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if User is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"Invalid credentials")
            return redirect('login')

    return render(request,"login.html")
def logout(request):
    auth.logout(request)
    return redirect('/')

cinemaproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter your movie name">
  <br>
  <input type="text" name="desc" placeholder="Enter the description">
  <br>
  <input type="number" name="year" placeholder="Enter the year">
  <br>
  <input type="file" name="img">
  <br>
  <input type="submit">

</form>
{% endblock %}

cinemaproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Hidden brand</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

cinemaproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  Are you sure want to delete?
  <button type="submit">Confirm</button>

</form>
</body>
</html>

cinemaproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card" style="width:350px; height:100%;">
            <img class="card-img-top" src="{{movie.img.url}}" width="150" height="250" alt="Card image cap">
                <br>
            <div class="card-body">
            <h5 class="card-title">{{movie.name}}</h5>
            <p class="card-text">{{movie.desc}}</p>
            <a href="{% url 'cinemaapp:update' movie.id %}" class="btn btn-success">Update</a>
                <a href="{% url 'cinemaapp:delete' movie.id %}" class="btn btn-danger">Delete</a>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

cinemaproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in result %}
        <div class="col-md-3">
            <div class="card" style="width:250px; height:100%;">
            <img class="card-img-top" src="{{i.img.url}}" width="150" height="200" alt="Card image cap">
                <br>
            <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
<!--            <p class="card-text">{{i.desc}}</p>-->
            <a href="{% url 'cinemaapp:detail' i.id %}" class="btn btn-warning">View Details</a>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!--{{i.desc}}-->
<!--<br>-->
<!--{{i.year}}-->
<br>
{% endblock %}

cinemaproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Login Form</h1>
<br>
<form action="login" method="post">
  {% csrf_token %}
<input type="text" name="username" placeholder="Enter the username">
<br>
<input type="password" name="password" placeholder="Enter the password">
<br>
<button><b>Login</b></button>
</form>
</body>
</html>

cinemaproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Registration Form</h2>
<br>
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter the username">
    <br>
    <input type="text" name="first_name" placeholder="Enter the first name">
    <br>
    <input type="text" name="last_name" placeholder="Enter the last name">
    <br>
    <input type="email" name="email" placeholder="Enter the email">
    <br>
    <input type="password" name="password" placeholder="Enter the password">
    <br>
    <input type="password" name="password1" placeholder="Confirm the password">
    <br>
    <button><b>Register</b></button>
</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
</body>
</html>

cinemaproject/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Addition is {{addition}}</h1>
<br>
<h1>Subtraction is {{subtraction}}</h1>
<br>
<h1>Multiplication is {{multiplication}}</h1>
<br>
<h1>Division is {{division}}</h1>
</body>
</html>

cinemaproject/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
    <button type="submit">Update</button>

</form>
</body>
</html>
